/**
 * This file is part of a commercial IRC bot that 
 * allows users to play online IRC games.
 * 
 * The project was commissioned by Julian Clark
 * 
 * Copyright (C) 2013 Jamie Reid
 */ 
package org.smokinmils.bot.events;

import org.smokinmils.bot.IrcBot;

import org.pircbotx.hooks.events.ActionEvent;

/**
 * Called whenever an ACTION is sent from a user.
 * E.g such events generated by typing "/me goes shopping" in most IRC clients.
 * 
 * @author Jamie
 */ 
public class Action extends ActionEvent<IrcBot> {
    /**
     * Constructor for the event.
     * 
     * @param event The action event. 
     * 
     * @see org.pircbotx.hooks.type.ActionEvent
     */
	public Action(final ActionEvent<IrcBot> event) {
		super(event.getBot(), event.getUser(),
		      event.getChannel(), event.getMessage());
	}
}
