/**
 * This file is part of a commercial IRC bot that 
 * allows users to play online IRC games.
 * 
 * The project was commissioned by Julian Clark
 * 
 * Copyright (C) 2013 Jamie Reid
 */ 
package org.smokinmils.bot.events;

import org.smokinmils.bot.IrcBot;

import org.pircbotx.Channel;
import org.pircbotx.User;
import org.pircbotx.hooks.events.ActionEvent;

/**
 * Called whenever an ACTION is sent from a user. E.g. such events generated by typing "/me goes shopping" in most IRC clients.
 * 
 * @author Jamie
 */
public class Action extends ActionEvent<IrcBot> {
	/**
	 * Constructor for the event
	 * @param bot
	 * @param user The user object representing the user that sent the message
	 * @param channel The channel object representing the target channel of the action. A value of null means that this is is a private message, not a channel
	 * @param action The action carried out by the user.
	 */
	public Action(IrcBot bot, User user, Channel channel, String action) {
		super(bot, user, channel, action);
	}
}
